from enum import StrEnum


class TaskStatus(StrEnum):
    RECEIVED = "RECEIVED"
    INTAKE = "INTAKE"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    CASE_ANALYSIS = "CASE_ANALYSIS"
    ROUTING = "ROUTING"
    REVIEWING = "REVIEWING"
    WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
    CREATE_LOCAL_CASE = "CREATE_LOCAL_CASE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class ReviewDecision(StrEnum):
    APPROVE = "APPROVE"
    RETURN = "RETURN"
    ASK_USER = "ASK_USER"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class HarnessPhase(StrEnum):
    APPEND_EVENT = "APPEND_EVENT"
    EXTRACT_FACTS = "EXTRACT_FACTS"
    RESOLVE_FACTS = "RESOLVE_FACTS"
    HYDRATE_MEMORY = "HYDRATE_MEMORY"
    COMPRESS_IF_NEEDED = "COMPRESS_IF_NEEDED"
    SELECT_WORKFLOW_STEP = "SELECT_WORKFLOW_STEP"
    RUN_AGENT = "RUN_AGENT"
    VALIDATE_PROPOSAL = "VALIDATE_PROPOSAL"
    EXECUTE_TOOLS = "EXECUTE_TOOLS"
    REDUCE_STATE = "REDUCE_STATE"
    PERSIST_MEMORY = "PERSIST_MEMORY"
    CHECKPOINT = "CHECKPOINT"
